version: "3.9"

services:
  mysqldb-server:
    image: 1fecb86b5237
    hostname: mysqldb-server
    container_name: mysqldb-server
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: serverpass
  mysqldb-client:
    image: 1fecb86b5237
    hostname: mysqldb-server
    container_name: mysqldb-client
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: clientpass
  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
