version: "3.9"

services:
  wordpress:
    image: wordpress:6.2.2-fpm-alpine
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: host.docker.internal
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: serverpass
      WORDPRESS_DB_NAME: ws_db
    volumes:
      - wordpress:/var/www/html
  # mysqldb-server:
  #   image: 1fecb86b5237
  #   hostname: mysqldb-server
  #   container_name: mysqldb-server
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: serverpass
  #
  # mysqldb-client:
  #   image: 1fecb86b5237
  #   hostname: mysqldb-client
  #   container_name: mysqldb-client
  #   ports:
  #     - 3307:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: clientpass
  #
  # rabbitmq:
  #   image: rabbitmq
  #   hostname: rabbitmq
  #   container_name: rabbitmq
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
volumes:
  wordpress:
