#Database
DATABASE_HOST="127.0.0.1"
DATABASE_PORT=3306
DATABASE_USER="root"
DATABASE_PASSWORD=""
DATABASE_NAME="db_rabbitmq_server"

#RabbitMQ Server
RABBITMQ_SERVER_HOST="127.0.0.1"
RABBITMQ_SERVER_PORT=""

#Database Sync Client
HOST_ID=0
HOST_NAME="SERVER"
HOST_QUEUE="server_queue"