server: Server Producer

server-exchange: Server Exchange {
  shape: oval
}


client-1-queue: Client 1 Queue {
  shape: queue
}

client-1-consumer: Client 1 Consumer

client-2-queue: Client 2 Queue {

  shape: queue
}

client-2-consumer: Client 2 Consumer

server -> server-exchange: .1.2. {
  style: {
    stroke: green
    font-color: green
    bold: true
    font-size: 24
  }
}

server-exchange -> client-1-queue: Yes {
  style: {

    stroke: green
    font-color: green
    bold: true

    font-size: 24
  }
}
server-exchange -> client-2-queue: Yes {

  style: {
    stroke: green
    font-color: green
    bold: true
    font-size: 24
  }
}


client-1-queue <- client-1-consumer: '#.1.#' {
  style: {

    stroke: green
    font-color: green
    bold: true
    font-size: 24
  }
}

client-2-queue <- client-2-consumer: '#.2.#' {
  style: {
    stroke: green
    font-color: green
    bold: true
    font-size: 24
  }
}

