direction: right
server: Server Producer

server-exchange: Server\nTopic Exchange {
  shape: oval
}

client-1-queue: Client 1\nQueue {
  shape: queue
}

client-1-consumer: Client 1\nConsumer

client-2-queue: Client 2\nQueue {
  shape: queue
}

client-2-consumer: Client 2\nConsumer

server -> server-exchange: .2. {
  style: {
    stroke: green
    font-color: green
    bold: true
    font-size: 24
  }
}

server-exchange -> client-1-queue: No {
  style: {
    stroke: red
    font-color: red
    bold: true

    font-size: 24
  }
}
server-exchange -> client-2-queue: Yes {
  style: {
    stroke: green
    font-color: green
    bold: true
    font-size: 24
  }
}

client-1-queue <- client-1-consumer: '#.1.#' {
  style: {
    stroke: red
    font-color: red
    bold: true
    font-size: 24
  }
}

client-2-queue <- client-2-consumer: '#.2.#' {
  style: {
    stroke: green
    font-color: green
    bold: true
    font-size: 24
  }
}

